### ISSUE TITLE
Data manager : neXtProt data table

### ISSUE THREAD

**Issue by yvandenb** [ifb-git/ProteoRE#278]
History "test_dataManager" shared with David 
While performing the update of some resources (logged as admin) met some problems with neXtprot
![image](https://user-images.githubusercontent.com/29478729/80975863-f80f3580-8e22-11ea-9af8-03ce1cb6791d.png)
With the following error msg: 
```
Traceback (most recent call last):
  File "/home/proteore/shed_tools/toolshed.g2.bx.psu.edu/repos/proteore/proteore_data_manager/b05fa99ddda2/proteore_data_manager/data_manager/resource_building.py", line 688, in <module>
    main()
  File "/home/proteore/shed_tools/toolshed.g2.bx.psu.edu/repos/proteore/proteore_data_manager/b05fa99ddda2/proteore_data_manager/data_manager/resource_building.py", line 681, in main
    Build_nextprot_ref_file(data_manager_dict,target_directory)
  File "/home/proteore/shed_tools/toolshed.g2.bx.psu.edu/repos/proteore/proteore_data_manager/b05fa99ddda2/proteore_data_manager/data_manager/resource_building.py", line 555, in Build_nextprot_ref_file
    data = resp.json()
  File "/home/proteore/galaxy/.venv/lib/python2.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/proteore/galaxy/.venv/lib/python2.7/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/home/proteore/galaxy/.venv/lib/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/proteore/galaxy/.venv/lib/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
  File "/home/proteore/galaxy/.venv/lib/python2.7/site-packages/simplejson/scanner.py", line 79, in scan_once
    return _scan_once(string, idx)
  File "/home/proteore/galaxy/.venv/lib/python2.7/site-packages/simplejson/scanner.py", line 70, in _scan_once
    raise JSONDecodeError(errmsg, string, idx)
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by davidchristiany** [comment]
Fixed on the last version of the data manager, it can sometimes fails due to the nextprot API, in that case just run it again. 
Both proteore.org and proteore-migale are up to date.

**Comment by yvandenb** [comment]
Thx David, that's great...though I reopen this issue...I ran yesterday datamanager selecting neXtprot, the tool is still running 24h lateer; we actually have an issue with neXprot REST API....the reason why remaining to be investigated to find a way to improve the duration of data retrieval, otherwise we'll have to identify an alternative way...anyway we should get in touch with neXprot colleagues

**Comment by yvandenb** [comment]
We initially thought to use a SPARQL query instead of the REST API to retrieve all the nextprot entries; however we were informed that SPARQL is a layer working upon REST, so we decided to give up 
=> we therefore decided to continue like this given that neXtprot is release once a year
