### ISSUE TITLE
proteore.org: Filter by keywords and/or numerical value (Galaxy Version 2019.06.27)

### ISSUE THREAD

**Issue by yvandenb** [ifb-git/ProteoRE#280]
history : uPE1_MaleTissue_April2020
shared with David
![image](https://user-images.githubusercontent.com/29478729/81825120-862ba000-9536-11ea-9aa8-d57382fc37b5.png)
input file used: Output from ID converter
INFO: 
Traceback (most recent call last):
  File "/home/proteore/shed_tools/toolshed.g2.bx.psu.edu/repos/proteore/proteore_filter_keywords_values/5621406a4d2f/proteore_filter_keywords_values/filter_kw_val.py", line 379, in <module>
    options()
  File "/home/proteore/shed_tools/toolshed.g2.bx.psu.edu/repos/proteore/proteore_filter_keywords_values/5621406a4d2f/proteore_filter_keywords_values/filter_kw_val.py", line 35, in options
    filters(args)
  File "/home/proteore/shed_tools/toolshed.g2.bx.psu.edu/repos/proteore/proteore_filter_keywords_values/5621406a4d2f/proteore_filter_keywords_values/filter_kw_val.py", line 79, in filters
    results_dict=filter_keyword(csv_file, header, results_dict, k[0], k[1], k[2])
  File "/home/proteore/shed_tools/toolshed.g2.bx.psu.edu/repos/proteore/proteore_filter_keywords_values/5621406a4d2f/proteore_filter_keywords_values/filter_kw_val.py", line 253, in filter_keyword
    keyword_inline = line[ncol].replace('"', "").split(";")
IndexError: list index out of range

**Comment by yvandenb** [comment]
@David: can you go through this issue, check, fix (if needed) and close it, please ?

**Comment by davidchristiany** [comment]
Your file (101) has not the same number betwen the top and the bottom.
it has 23 colums for the 710 first line and 10 after that.
Since your filter is on the column 22 it cause an error at the line 711 because the column does not exist.
