### ISSUE TITLE
Data manager: ID Mapping Fatal error: Exit code 1 ()

### ISSUE THREAD

**Issue by yvandenb** [ifb-git/ProteoRE#281]
Instance : dev proteore-migale
History shared with David and Valentin
![image](https://user-images.githubusercontent.com/29478729/83943415-2d30ee00-a7fc-11ea-812a-e1cbdbd65ff4.png)
Traceback (most recent call last):
  File "/projet/galaxyprod/proteore2/shed_tools/testtoolshed.g2.bx.psu.edu/repos/proteore/proteore_data_manager/bb552aa4b9ac/proteore_data_manager/data_manager/resource_building.py", line 689, in <module>
    main()
  File "/projet/galaxyprod/proteore2/shed_tools/testtoolshed.g2.bx.psu.edu/repos/proteore/proteore_data_manager/bb552aa4b9ac/proteore_data_manager/data_manager/resource_building.py", line 661, in main
    id_mapping_sources(data_manager_dict, species, target_directory, args.tool_data_path)
  File "/projet/galaxyprod/proteore2/shed_tools/testtoolshed.g2.bx.psu.edu/repos/proteore/proteore_data_manager/bb552aa4b9ac/proteore_data_manager/data_manager/resource_building.py", line 239, in id_mapping_sources
    with open(nextprot_path,'r') as nextprot_ids :
TypeError: coercing to Unicode: need string or buffer, list found

**Comment by davidchristiany** [comment]
I fixed it on the last version of  the data manager. 
Proteore.org and proteore-migale are both up to date.
