### ISSUE TITLE
proteore_data_manager: "No such file or directory"

### ISSUE THREAD

**Issue by abretaud** [ifb-git/ProteoRE#288]
Bonjour,
Un problème rencontré sur l'instance de preprod de usegalaxy.fr :
```
Traceback (most recent call last):
  File "/shared/mfs/data/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/proteore/proteore_data_manager/b8565596bb25/proteore_data_manager/data_manager/resource_building.py", line 737, in <module>
    main()
  File "/shared/mfs/data/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/proteore/proteore_data_manager/b8565596bb25/proteore_data_manager/data_manager/resource_building.py", line 709, in main
    id_mapping_sources(data_manager_dict, species, target_directory, args.tool_data_path)
  File "/shared/mfs/data/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/proteore/proteore_data_manager/b8565596bb25/proteore_data_manager/data_manager/resource_building.py", line 145, in id_mapping_sources
    if os.path.isdir(archive) is False : os.mkdir(archive)
FileNotFoundError: [Errno 2] No such file or directory: '/shared/mfs/data/galaxy/mutable-config/tool-data/id_mapping/ID_mapping_archive_Human_20210107'
```
Je pense qu'il faudrait juste que le code vérifie l'existence du répertoire `id_mapping` avant de tenter d'y créer un sous-répertoire

**Comment by abretaud** [comment]
Une autre erreur après avoir fait un mkdir manuel : 

```
Traceback (most recent call last):
  File "/shared/mfs/data/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/proteore/proteore_data_manager/b8565596bb25/proteore_data_manager/data_manager/resource_building.py", line 737, in <module>
    main()
  File "/shared/mfs/data/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/proteore/proteore_data_manager/b8565596bb25/proteore_data_manager/data_manager/resource_building.py", line 734, in main
    open(filename, 'wb').write(to_json_string(data_manager_dict))
TypeError: a bytes-like object is required, not 'str'
```
